# Generated by Django 6.0.2 on 2026-06-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id_ajuste', models.AutoField(db_column='id_ajuste', primary_key=True, serialize=False)),
                ('fecha_ajuste', models.DateTimeField(db_column='fecha_ajuste')),
                ('tipo_ajuste', models.CharField(choices=[('DAÑADO', 'Dañado'), ('ROBO', 'Robo'), ('PERDIDA', 'Pérdida'), ('CADUCADO', 'Caducado'), ('MUESTRA', 'Muestra')], db_column='tipo_ajuste', max_length=20)),
                ('cantidad_ajustada', models.IntegerField(db_column='cantidad_ajustada')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ajuste_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AjusteInventarioMatPrima',
            fields=[
                ('id_ajust_mat', models.AutoField(db_column='id_ajus_mat', primary_key=True, serialize=False)),
                ('fecha_ajust_mat', models.DateTimeField(db_column='fecha_ajus_mat')),
                ('tipo_ajust_mat', models.CharField(choices=[('DAÑADO', 'Dañado'), ('ROBO', 'Robo'), ('PERDIDA', 'Pérdida'), ('CADUCADO', 'Caducado')], db_column='tipo_ajus_mat', max_length=20)),
                ('cantidad_ajustada_mat', models.DecimalField(db_column='cantidad_ajustada_mat', decimal_places=3, max_digits=10)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion_ajust_mat', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ajuste_materia_prima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id_materia_prima', models.BigAutoField(db_column='id_materia_prima', primary_key=True, serialize=False)),
                ('nombre_materia_prima', models.CharField(db_column='nombre_materia_prima', max_length=50)),
                ('fecha_vencimiento_mat_prima', models.DateField(db_column='fecha_vencimiento_materia_prima')),
                ('cantidad_exist_mat_prima', models.DecimalField(db_column='cantidad_exist_materia_prima', decimal_places=3, max_digits=10)),
                ('presentacion_mat_prima', models.CharField(choices=[('KG', 'Kilogramos'), ('LT', 'Litros'), ('UN', 'Unidades')], db_column='presentacion_materia_prima', max_length=20)),
                ('descripcion_mat_prima', models.CharField(blank=True, db_column='descripcion_materia_prima', max_length=200, null=True)),
                ('estado_materia_prima', models.BooleanField(db_column='estado_materia_prima')),
            ],
            options={
                'db_table': 'materia_prima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(db_column='nombre_producto', max_length=50, unique=True)),
                ('imagen_producto', models.ImageField(blank=True, db_column='imagen_producto', null=True, upload_to='productos/')),
                ('valor_unitario_product', models.BigIntegerField(db_column='valor_unitario_producto')),
                ('cant_exist_producto', models.BigIntegerField(db_column='cant_exist_producto')),
                ('fecha_vencimiento_product', models.DateField(db_column='fecha_vencimiento_producto')),
                ('tipo_producto', models.CharField(choices=[('PANADERIA', 'Panadería'), ('PASTELERIA', 'Pastelería'), ('ASEO', 'Aseo'), ('REVENTA', 'Reventa')], db_column='tipo_producto', max_length=20)),
                ('descripcion_producto', models.CharField(blank=True, db_column='descripcion_producto', max_length=200, null=True)),
                ('estado_producto', models.BooleanField(db_column='estado_producto')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
