# Generated by Django 6.0.2 on 2026-06-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('num_doc', models.BigIntegerField(db_column='num_doc', unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('password', models.CharField(db_column='password_usuario', max_length=255)),
                ('tel_usuario', models.BigIntegerField(db_column='tel_usuario')),
                ('email_usuario', models.EmailField(db_column='email_usuario', max_length=50, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('estado_usuario', models.BooleanField(db_column='estado_usuario', default=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='rol', max_length=50)),
                ('clasificacion', models.CharField(choices=[('EMPLEADO', 'Empleado'), ('ADMINISTRADOR', 'Administrador')], db_column='clasificacion', max_length=20)),
                ('estado_rol', models.BooleanField(db_column='estado_rol', default=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
    ]
