# Generated by Django 6.0.2 on 2026-06-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.BigAutoField(db_column='id_compra', primary_key=True, serialize=False)),
                ('fecha_hora_compra', models.DateTimeField(db_column='fecha_hora_compra')),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, db_column='fecha_cambio_estado', null=True)),
                ('tipo', models.CharField(choices=[('MATERIA PRIMA', 'Materia Prima'), ('PRODUCTO TERMINADO', 'Producto Terminado')], db_column='tipo', max_length=20)),
                ('total_compra', models.BigIntegerField(db_column='total_compra')),
                ('descripcion_compra', models.CharField(blank=True, db_column='descripcion_compra', max_length=200, null=True)),
                ('estado_factura_compra', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], db_column='estado_factura_compra', max_length=20)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraMateriaPrima',
            fields=[
                ('id_det_compra_mat_prim', models.AutoField(db_column='id_det_compra_mat_prim', primary_key=True, serialize=False)),
                ('cantidad_mat_prima_comprada', models.DecimalField(db_column='cantidad_mat_prima_comprada', decimal_places=3, max_digits=10)),
                ('sub_total_mat_prima_comprada', models.BigIntegerField(db_column='sub_total_mat_prima_comprada')),
                ('estado_det_compra_mat_prima', models.BooleanField(db_column='estado_det_compra_mat_prima')),
            ],
            options={
                'db_table': 'detalle_compra_materia_prima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraProducto',
            fields=[
                ('id_det_compra_prod', models.AutoField(db_column='id_det_compra_prod', primary_key=True, serialize=False)),
                ('cantidad_prod_comprado', models.BigIntegerField(db_column='cantidad_prod_comprado')),
                ('sub_total_prod_comprado', models.BigIntegerField(db_column='sub_total_prod_comprado')),
                ('estado_det_compra_prod', models.BooleanField(db_column='estado_det_compra_prod')),
            ],
            options={
                'db_table': 'detalle_compra_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cedula_proveedor', models.BigIntegerField(db_column='cedula_proveedor', primary_key=True, serialize=False)),
                ('lugar_expedicion', models.CharField(db_column='lugar_expedicion', max_length=50)),
                ('nombre_proveedor', models.CharField(db_column='nombre_proveedor', max_length=50)),
                ('marca', models.CharField(db_column='marca', max_length=50)),
                ('tel_proveedor', models.BigIntegerField(db_column='tel_proveedor', unique=True)),
                ('email_proveedor', models.EmailField(db_column='email_proveedor', max_length=50, unique=True)),
                ('estado_proveedor', models.BooleanField(db_column='estado_proveedor')),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
    ]
