# Generated by Django 6.0.2 on 2026-06-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(db_column='id_detalle_venta', primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField(db_column='cantidad')),
                ('sub_total', models.BigIntegerField(db_column='sub_total')),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigAutoField(db_column='id_venta', primary_key=True, serialize=False)),
                ('fecha_hora_venta', models.DateTimeField(db_column='fecha_hora_venta')),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, db_column='fecha_cambio_estado', null=True)),
                ('total_venta', models.BigIntegerField(db_column='total_venta')),
                ('numero_mesa', models.IntegerField(blank=True, db_column='numero_mesa', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
                ('estado_pedido', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'Preparando'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], db_column='estado_pedido', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], db_column='estado_pago', max_length=20)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
