# Generated by Django 6.0.2 on 2026-06-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id_detalle_receta', models.AutoField(db_column='id_detalle_receta', primary_key=True, serialize=False)),
                ('cantidad_insumo_base', models.DecimalField(db_column='cantidad_insumo_base', decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(db_column='id_receta', primary_key=True, serialize=False)),
                ('nombre_receta', models.CharField(db_column='nombre_receta', max_length=100)),
                ('descripcion_receta', models.CharField(blank=True, db_column='descripcion_receta', max_length=255, null=True)),
                ('cantidad_base', models.BigIntegerField(db_column='cantidad_base', default=1)),
                ('estado_receta', models.BooleanField(db_column='estado_receta', default=True)),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
    ]
