# Generated by Django 6.0.2 on 2026-06-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProduccion',
            fields=[
                ('id_detalle_produccion', models.BigAutoField(db_column='id_detalle_produccion', primary_key=True, serialize=False)),
                ('cantidad_requerida', models.DecimalField(db_column='cantidad_requerida', decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id_produccion', models.BigAutoField(db_column='id_produccion', primary_key=True, serialize=False)),
                ('nombre_produccion', models.CharField(db_column='nombre_produccion', max_length=50)),
                ('fecha_hora_produccion', models.DateTimeField(db_column='fecha_hora_produccion')),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, db_column='fecha_cambio_estado', null=True)),
                ('categoria_produccion', models.CharField(db_column='categoria_produccion', max_length=50)),
                ('cant_produccion', models.BigIntegerField(db_column='cant_produccion')),
                ('descripcion_produccion', models.CharField(db_column='descripcion_produccion', max_length=200)),
                ('estado_produccion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_column='estado_produccion', max_length=20)),
            ],
            options={
                'db_table': 'produccion',
                'managed': False,
            },
        ),
    ]
